### ISSUE TITLE
invalid dependency

### ISSUE THREAD

**Issue by dzhivushko** [apigee-127/apigee-remote-proxy#3]
I have installed 'apigee-remote-proxy' from NPM:
"npm install -g apigee-remote-proxy"

The dependencies list seems to be incorrect

![screenshot_1](https://cloud.githubusercontent.com/assets/12233334/13178973/a5265b24-d732-11e5-9211-768b99b0af95.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/12233334/13178972/a5247836-d732-11e5-86c2-f5a16687df9f.png)

**Comment by theganyo** [comment]
Wow. Thanks for this report. I just pushed a new version that should be properly in sync. Please try and let me know that's all ok for you now.

**Comment by dzhivushko** [comment]
thank you, Scott!
Yes, the package.json looks fine now. Unfortunately can't come back to the work with 'remote-proxy' right now to check it's installation but dependencies list looks correct now
